### ISSUE TITLE
WiFi access point mode does not work on 2.0.4

### ISSUE THREAD

**Issue by dmitryelj** [TinkerBoard/debian_kernel#9] opened 2018-01-31 16:10 UTC
Hi all.

WiFi access point mode with **hostapd** works nice on 2.0.1 but stopped working on 2.0.4.

"sudo service hostapd status" error:
hostapd.service - LSB: Advanced IEEE 802.11 management daemon
Active: active (exited) since Wed 2018-01-31 09:19:22 UTC; 38s ago
Process: 630 ExecStart=/etc/init.d/hostapd start (code=exited, status=0/SUCCESS)
CGroup: /system.slice/hostapd.service

Jan 31 09:19:21 tinkerboard hostapd[630]: Starting advanced IEEE 802.11 management: hostapderror: unexpectedly disconnected from boot status daemon

The workaround was found on the forum https://tinkerboarding.co.uk/forum/thread-997.html but it looks like a bug anyway.

**Comment by Sam2Hsu** [comment] 2018-03-14 03:15
Hi dmitryelj,

Thanks for the information.

This issue caused by wpa_supplicant.service, it will occupy wlan0. So that hostapd couldn't launch with wlan0.

You can replace /lib/systemd/system/wpa_supplicant.service with below lines:
```[Unit]
Description=WPA supplicant
Before=network.target
After=dbus.service
Wants=network.target

[Service]
Type=dbus
BusName=fi.epitest.hostap.WPASupplicant
ExecStart=/sbin/wpa_supplicant -u -s -O /run/wpa_supplicant

[Install]
WantedBy=multi-user.target
Alias=dbus-fi.epitest.hostap.WPASupplicant.service
```

This issue will be fixed in a future release.

Thanks,
Sam

**Closed as completed** 2018-03-14 03:16 UTC
